# Generated by Django 5.2 on 2026-01-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentprofile_english_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
