# Generated by Django 5.2.3 on 2026-01-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_topic_studentweaktopic_learningcontent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcontent',
            name='concept_tag',
            field=models.CharField(blank=True, help_text="Tag for specific concept matching (e.g. 'friction')", max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='concept_tag',
            field=models.CharField(blank=True, help_text="Tag for specific concept (e.g. 'friction')", max_length=50),
        ),
        migrations.AddField(
            model_name='studentweaktopic',
            name='weak_concepts',
            field=models.TextField(blank=True, help_text='Comma-separated list of weak concept tags'),
        ),
    ]
