# Generated by Django 5.2 on 2026-01-25 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_question_topic_name'),
        ('student', '0004_topic_studentweaktopic_learningcontent_and_more'),
    ]

    operations = [
    ]
