# Generated by Django 5.2.3 on 2026-01-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_learningcontent_concept_tag_question_concept_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentweaktopic',
            name='study_plan',
            field=models.JSONField(blank=True, help_text='AI-generated 3-day study plan', null=True),
        ),
    ]
