# Generated by Django 5.2 on 2026-01-25 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_question_topic_name_alter_question_topic_and_more'),
        ('student', '0006_studentweaktopic_study_plan'),
    ]

    operations = [
    ]
